apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workspace-pipeline12-ref
spec:
  workspaces:
    - name: pipeline-ws
    #- name: docker-credentials
  tasks:
    - name: clone-task
      taskRef:
        name: clone-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
    - name: build-task
      taskRef:
        name: build-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - clone-task
    - name: sonar-task
      taskRef:
        name: sonar-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - build-task
    
    - name: kaniko-task
      taskRef:
        name: kaniko-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
        #- name: dockerconfig
        #  workspace: docker-credentials
      runAfter:
        - sonar-task
    - name: deploy-task
      taskRef:
        name: deploy-application
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - kaniko-task
