apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workspace-pipeline5-ref
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-task
      taskRef:
        name: clone-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
    - name: build-task
      taskRef:
        name: build-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - clone-task
    - name: sonar-task
      taskRef:
        name: sonar-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - build-task
    - name: buildah-task
      taskRef:
        name: buildah-task-ref
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
      runAfter:
        - sonar-task
