apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-gmstk-run
spec:
  workspaces:
    - name: pipeline-ws
      persistentVolumeClaim:
        claimName: example-local-claim
    - name: docker-credentials 
      secret:
        secretName: docker-credentials
  pipelineRef:
    name: workspace-pipeline6-ref
