apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-task-ref
spec:
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: clone-step
      image: bitnami/git
      workingDir: $(workspaces.task-ws.path)
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting initial task"
            rm -rf kaniko-image-building3
            git clone https://github.com/Gokul-C/DevOps-K8s-Security.git $(workspaces.task-ws.path)/kaniko-image-building3
            sleep 15
            ls -la $(workspaces.task-ws.path)/kaniko-image-building3
            echo "Ending clone task"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task-ref
spec:
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: build-task
      image: maven
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting build task - Reading file from workspace"
            cd $(workspaces.task-ws.path)/kaniko-image-building3
            mvn clean package
            echo "End final task"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonar-task-ref
spec:
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: sonar-task
      image: maven
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting sonar scanning task - Reading file from workspace"
            cd $(workspaces.task-ws.path)/kaniko-image-building3
            mvn clean verify sonar:sonar -Dsonar.projectKey=tekton-sonar -Dsonar.projectName='tekton-sonar' -Dsonar.host.url=http://10.0.1.38:9000 -Dsonar.token=sqp_f197446aaae8c2a83d5f09df398fef507afd7e01
            echo "End sonar scanning"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-task-ref
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: docker.io/gokulc780/tekton-image:v1
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
    - name: EXTRA_ARGS
      type: array
      default: []
    - name: BUILDER_IMAGE
      description: The image on which builds will run (default is v1.5.1)
      default: gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: kaniko-task
      image: $(params.BUILDER_IMAGE)
      workingDir: $(workspaces.task-ws.path)/kaniko-image-building3
      env:
        - name: DOCKER_CONFIG
          value: docker-creds
      securityContext:
        runAsUser: 0
      command:
        - /kaniko/executor
        - $(params.EXTRA_ARGS)
        - --dockerfile=$(params.DOCKERFILE)
        - --context=.  # The user does not need to care the workspace and the source.
        - --destination=$(params.IMAGE)
        - --oci-layout-path=$(workspaces.task-ws.path)/kaniko-image-building3/image-digest
