apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-task-ref
spec:
  params:
    - name: github-url
      description: url of the repo.
      default: https://github.com/Gokul-C/DevOps-K8s-Security.git
    - name: directory
      description: name of the directory inside workspace
      default: kaniko-image-building3
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: clone-step
      image: bitnami/git
      workingDir: $(workspaces.task-ws.path)
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting initial task"
            rm -rf kaniko-image-building3
            git clone https://github.com/Gokul-C/DevOps-K8s-Security.git $(workspaces.task-ws.path)/$(params.directory)
            sleep 15
            ls -la $(workspaces.task-ws.path)/$(params.directory)
            echo "Ending clone task"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task-ref
spec:
  params:
    - name: directory
      description: name of the directory inside workspace
      default: kaniko-image-building3
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: build-task
      image: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641 #tag: latest
      workingDir: $(workspaces.task-ws.path)/$(params.directory)
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting build task - Reading file from workspace"
            #cd $(workspaces.task-ws.path)/kaniko-image-building3
            mvn clean package
            echo "End final task"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonar-task-ref
spec:
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
  steps:
    - name: sonar-task
      image: maven
      securityContext:
        runAsUser: 0
      command: ["/bin/sh"]
      args:
        - -c
        - |
            echo "Starting sonar scanning task - Reading file from workspace"
            cd $(workspaces.task-ws.path)/kaniko-image-building3
            mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tekton2127_tekton -Dsonar.token=48122b4df02e0a9156056177d9acf9292a436336
            echo "End sonar scanning"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-task-ref
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: gokulc780/tekton-image:v1
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
    - name: EXTRA_ARGS
      type: array
      default: []
    - name: BUILDER_IMAGE
      description: The image on which builds will run (default is v1.5.1)
      default: gcr.io/kaniko-project/executor:debug
  workspaces:
    - name: task-ws
      description: Workspace for sharing files between tasks
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
  steps:
    - name: kaniko-task
      image: $(params.BUILDER_IMAGE)
      workingDir: $(workspaces.task-ws.path)/kaniko-image-building3
      #env:
      #  - name: DOCKER_CONFIG
      #    value: docker-creds
      securityContext:
        runAsUser: 0
      command:
        - /kaniko/executor
        - $(params.EXTRA_ARGS)
        - --dockerfile=$(params.DOCKERFILE)
        - --context=.  # The user does not need to care the workspace and the source.
        - --destination=$(params.IMAGE)
        - --oci-layout-path=$(workspaces.task-ws.path)/kaniko-image-building3/image-digest
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-application
spec:
    params:
      - name: pathToContext
        description: The path to the build context, used by Kaniko - within the workspace
        default: .
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
        default: $(workspaces.task-ws.path)/kaniko-image-building3/deployment.yaml
      - name: imageUrl
        description: Url of image repository
        default: url
      - name: imageTag
        description: Tag of the images to be used.
        default: "v1"
    workspaces:
    - name: task-ws
    steps:
      - name: deploy-app
        image: gcr.io/cloud-builders/kubectl@sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753
        command: ["kubectl"]
        args:
          - "apply"
          - "-f"
          - "$(inputs.params.pathToYamlFile)"
